# Generated by Django 5.2.4 on 2025-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_privatemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='private_chat/'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
