# Generated by Django 5.2.4 on 2025-11-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_privatemessage_options_privatemessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
