# Generated by Django 5.2.4 on 2025-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_profile_is_online_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
